name: Make Docs
on:
  pull_request:
    branches: ["master"]
  push:
    branches:
        - master
    tags: '*'
  workflow_dispatch:
    
jobs:
  make_docs:
    permissions:
      contents: write
      statuses: write
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
      - uses: julia-actions/cache@v1
      - name: Add FuseRegistry
        run: |
          julia --project=docs/ -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url="https://github.com/ProjectTorreyPines/FuseRegistry.jl.git")); Pkg.Registry.add("General")'
      - name: Install dependencies
        run: |
          julia -e '
            using Pkg
            Pkg.activate("docs")
            
            dependencies = PackageSpec[]
            for package in ("MillerExtendedHarmonic", "FXP", "FuseUtils")
              push!(dependencies, PackageSpec(url="https://project-torrey-pines:${{secrets.PTP_READ_TOKEN}}@github.com/ProjectTorreyPines/$package.jl.git"))
            end
            Pkg.add(dependencies)
            println("DONE with GIT deps")
            
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
            '
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia --project=docs/ docs/make.jl